// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// Export file: ../Assets/Scripts/behaviac/exported/behaviac_generated/behaviors/generated_behaviors.cs
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;

namespace behaviac
{
	// Source file: HoverBotBT

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_HoverBotBT_node3 : behaviac.Condition
	{
		public Condition_bt_HoverBotBT_node3()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			bool opl = ((HoverBotAgent)pAgent).HasTarget();
			bool opr = false;
			bool op = opl == opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_HoverBotBT_node1 : behaviac.Action
	{
		public Action_bt_HoverBotBT_node1()
		{
			this.m_resultOption = EBTStatus.BT_INVALID;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			behaviac.EBTStatus result = ((HoverBotAgent)pAgent).DoPatrol();
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Parallel_bt_HoverBotBT_node11 : behaviac.Parallel
	{
		public Parallel_bt_HoverBotBT_node11()
		{
			m_failPolicy = behaviac.FAILURE_POLICY.FAIL_ON_ONE;
			m_succeedPolicy = behaviac.SUCCESS_POLICY.SUCCEED_ON_ALL;
			m_exitPolicy = behaviac.EXIT_POLICY.EXIT_ABORT_RUNNINGSIBLINGS;
			m_childFinishPolicy = behaviac.CHILDFINISH_POLICY.CHILDFINISH_LOOP;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_HoverBotBT_node6 : behaviac.Action
	{
		public Action_bt_HoverBotBT_node6()
		{
			this.m_resultOption = EBTStatus.BT_INVALID;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			behaviac.EBTStatus result = ((HoverBotAgent)pAgent).DoAttack();
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_HoverBotBT_node8 : behaviac.Condition
	{
		public Condition_bt_HoverBotBT_node8()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			float opl = ((HoverBotAgent)pAgent).GetTargetDist();
			float opr = 4f;
			bool op = opl < opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_HoverBotBT_node10 : behaviac.Action
	{
		public Action_bt_HoverBotBT_node10()
		{
			this.m_resultOption = EBTStatus.BT_INVALID;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			behaviac.EBTStatus result = ((HoverBotAgent)pAgent).StopChase();
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_HoverBotBT_node7 : behaviac.Action
	{
		public Action_bt_HoverBotBT_node7()
		{
			this.m_resultOption = EBTStatus.BT_INVALID;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			behaviac.EBTStatus result = ((HoverBotAgent)pAgent).DoChase();
			return result;
		}
	}

	public static class bt_HoverBotBT
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("HoverBotBT");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("HoverBotAgent");
#endif
			// children
			{
				Selector node0 = new Selector();
				node0.SetClassNameString("Selector");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("HoverBotAgent");
#endif
				bt.AddChild(node0);
				{
					Sequence node2 = new Sequence();
					node2.SetClassNameString("Sequence");
					node2.SetId(2);
#if !BEHAVIAC_RELEASE
					node2.SetAgentType("HoverBotAgent");
#endif
					node0.AddChild(node2);
					{
						Condition_bt_HoverBotBT_node3 node3 = new Condition_bt_HoverBotBT_node3();
						node3.SetClassNameString("Condition");
						node3.SetId(3);
#if !BEHAVIAC_RELEASE
						node3.SetAgentType("HoverBotAgent");
#endif
						node2.AddChild(node3);
						node2.SetHasEvents(node2.HasEvents() | node3.HasEvents());
					}
					{
						Action_bt_HoverBotBT_node1 node1 = new Action_bt_HoverBotBT_node1();
						node1.SetClassNameString("Action");
						node1.SetId(1);
#if !BEHAVIAC_RELEASE
						node1.SetAgentType("HoverBotAgent");
#endif
						node2.AddChild(node1);
						node2.SetHasEvents(node2.HasEvents() | node1.HasEvents());
					}
					node0.SetHasEvents(node0.HasEvents() | node2.HasEvents());
				}
				{
					Parallel_bt_HoverBotBT_node11 node11 = new Parallel_bt_HoverBotBT_node11();
					node11.SetClassNameString("Parallel");
					node11.SetId(11);
#if !BEHAVIAC_RELEASE
					node11.SetAgentType("HoverBotAgent");
#endif
					node0.AddChild(node11);
					{
						Action_bt_HoverBotBT_node6 node6 = new Action_bt_HoverBotBT_node6();
						node6.SetClassNameString("Action");
						node6.SetId(6);
#if !BEHAVIAC_RELEASE
						node6.SetAgentType("HoverBotAgent");
#endif
						node11.AddChild(node6);
						node11.SetHasEvents(node11.HasEvents() | node6.HasEvents());
					}
					{
						Selector node4 = new Selector();
						node4.SetClassNameString("Selector");
						node4.SetId(4);
#if !BEHAVIAC_RELEASE
						node4.SetAgentType("HoverBotAgent");
#endif
						node11.AddChild(node4);
						{
							Sequence node9 = new Sequence();
							node9.SetClassNameString("Sequence");
							node9.SetId(9);
#if !BEHAVIAC_RELEASE
							node9.SetAgentType("HoverBotAgent");
#endif
							node4.AddChild(node9);
							{
								Condition_bt_HoverBotBT_node8 node8 = new Condition_bt_HoverBotBT_node8();
								node8.SetClassNameString("Condition");
								node8.SetId(8);
#if !BEHAVIAC_RELEASE
								node8.SetAgentType("HoverBotAgent");
#endif
								node9.AddChild(node8);
								node9.SetHasEvents(node9.HasEvents() | node8.HasEvents());
							}
							{
								Action_bt_HoverBotBT_node10 node10 = new Action_bt_HoverBotBT_node10();
								node10.SetClassNameString("Action");
								node10.SetId(10);
#if !BEHAVIAC_RELEASE
								node10.SetAgentType("HoverBotAgent");
#endif
								node9.AddChild(node10);
								node9.SetHasEvents(node9.HasEvents() | node10.HasEvents());
							}
							node4.SetHasEvents(node4.HasEvents() | node9.HasEvents());
						}
						{
							Action_bt_HoverBotBT_node7 node7 = new Action_bt_HoverBotBT_node7();
							node7.SetClassNameString("Action");
							node7.SetId(7);
#if !BEHAVIAC_RELEASE
							node7.SetAgentType("HoverBotAgent");
#endif
							node4.AddChild(node7);
							node4.SetHasEvents(node4.HasEvents() | node7.HasEvents());
						}
						node11.SetHasEvents(node11.HasEvents() | node4.HasEvents());
					}
					node0.SetHasEvents(node0.HasEvents() | node11.HasEvents());
				}
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

}
